version: '3.1'
services:
  db:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=hibernate_demo
      - POSTGRES_PASSWORD=hibernate_demo
      - POSTGRES_DB=hsearch_es_wikipedia
    volumes:
      - postgresdata1:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgresnet
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  postgresdata1:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
  postgresnet:
